/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleResponse } from '../../models/role-response';

export interface ApiRolesGet$Json$Params {
}

export function apiRolesGet$Json(http: HttpClient, rootUrl: string, params?: ApiRolesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiRolesGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RoleResponse>>;
    })
  );
}

apiRolesGet$Json.PATH = '/api/Roles';
