/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArticleResponse {
  active: boolean;
  author: string;
  content: string;
  createdAt: string;
  id: string;
  isPublished: boolean;
  publishedAt: (string | null);
  slug: string;
  title: string;
  updatedAt: (string | null);
}
