/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateShowroomItemRequest {
  category: string;
  description: string;
  price: (number | string);
  title: string;
}
