/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MemberResponse {
  acceptNews: boolean;
  acceptPromo: boolean;
  active: boolean;
  createdAt: string;
  displayName: string;
  email: string;
  firstName: string;
  id: string;
  lastName: string;
  updatedAt: (string | null);
}
