/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ShowroomItemResponse } from '../models/showroom-item-response';
export interface PagedResponseOfShowroomItemResponse {
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  items: Array<ShowroomItemResponse>;
  pageNumber: (number | string);
  pageSize: (number | string);
  totalCount: (number | string);
  totalPages?: (number | string);
}
