/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArticleResponse } from '../models/article-response';
export interface PagedResponseOfArticleResponse {
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  items: Array<ArticleResponse>;
  pageNumber: (number | string);
  pageSize: (number | string);
  totalCount: (number | string);
  totalPages?: (number | string);
}
