/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
  acceptNews: boolean;
  acceptPromo: boolean;
  displayName: string;
  email: string;
  firstName: string;
  lastName: string;
  password: string;
}
