/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ShowroomItemPhotoResponse } from '../models/showroom-item-photo-response';
export interface ShowroomItemResponse {
  active: boolean;
  category: string;
  createdAt: string;
  description: string;
  id: string;
  photos: Array<ShowroomItemPhotoResponse>;
  price: (number | string);
  title: string;
  updatedAt: (string | null);
}
