/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateMarketingPreferencesRequest {
  acceptNews: boolean;
  acceptPromo: boolean;
  consentToken: (string | null);
  consentedAt: (string | null);
}
