/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShowroomItemResponse } from '../../models/showroom-item-response';

export interface ApiShowroomItemsIdGet$Json$Params {
  id: string;
}

export function apiShowroomItemsIdGet$Json(http: HttpClient, rootUrl: string, params: ApiShowroomItemsIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ShowroomItemResponse>> {
  const rb = new RequestBuilder(rootUrl, apiShowroomItemsIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShowroomItemResponse>;
    })
  );
}

apiShowroomItemsIdGet$Json.PATH = '/api/ShowroomItems/{id}';
