/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedResponseOfShowroomItemResponse } from '../../models/paged-response-of-showroom-item-response';

export interface ApiShowroomItemsGet$Json$Params {
  page?: (number | string);
  pageSize?: (number | string);
}

export function apiShowroomItemsGet$Json(http: HttpClient, rootUrl: string, params?: ApiShowroomItemsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedResponseOfShowroomItemResponse>> {
  const rb = new RequestBuilder(rootUrl, apiShowroomItemsGet$Json.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedResponseOfShowroomItemResponse>;
    })
  );
}

apiShowroomItemsGet$Json.PATH = '/api/ShowroomItems';
