/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddShowroomItemPhotoRequest } from '../../models/add-showroom-item-photo-request';

export interface ApiShowroomItemsIdPhotosPost$Json$Params {
  id: string;
      body: AddShowroomItemPhotoRequest
}

export function apiShowroomItemsIdPhotosPost$Json(http: HttpClient, rootUrl: string, params: ApiShowroomItemsIdPhotosPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, apiShowroomItemsIdPhotosPost$Json.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

apiShowroomItemsIdPhotosPost$Json.PATH = '/api/ShowroomItems/{id}/photos';
