/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedResponseOfArticleResponse } from '../../models/paged-response-of-article-response';

export interface ApiArticlesGet$Json$Params {
  page?: (number | string);
  pageSize?: (number | string);
  onlyPublished?: boolean;
}

export function apiArticlesGet$Json(http: HttpClient, rootUrl: string, params?: ApiArticlesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedResponseOfArticleResponse>> {
  const rb = new RequestBuilder(rootUrl, apiArticlesGet$Json.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('onlyPublished', params.onlyPublished, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedResponseOfArticleResponse>;
    })
  );
}

apiArticlesGet$Json.PATH = '/api/Articles';
