/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AddShowroomItemPhotoRequest } from './models/add-showroom-item-photo-request';
export type { ArticleResponse } from './models/article-response';
export type { AssignRoleRequest } from './models/assign-role-request';
export type { ChangeEmailRequest } from './models/change-email-request';
export type { ChangePasswordRequest } from './models/change-password-request';
export type { ConfirmEmailRequest } from './models/confirm-email-request';
export type { CreateArticleRequest } from './models/create-article-request';
export type { CreateRoleRequest } from './models/create-role-request';
export type { CreateShowroomItemRequest } from './models/create-showroom-item-request';
export type { LoginRequest } from './models/login-request';
export type { MemberResponse } from './models/member-response';
export type { PagedResponseOfArticleResponse } from './models/paged-response-of-article-response';
export type { PagedResponseOfShowroomItemResponse } from './models/paged-response-of-showroom-item-response';
export type { ProblemDetails } from './models/problem-details';
export type { PublishArticleRequest } from './models/publish-article-request';
export type { PurgeUserRequest } from './models/purge-user-request';
export type { RefreshRequest } from './models/refresh-request';
export type { RegisterRequest } from './models/register-request';
export type { ResendConfirmationEmailRequest } from './models/resend-confirmation-email-request';
export type { RoleResponse } from './models/role-response';
export type { ShowroomItemPhotoResponse } from './models/showroom-item-photo-response';
export type { ShowroomItemResponse } from './models/showroom-item-response';
export type { TokenResponse } from './models/token-response';
export type { UpdateArticleRequest } from './models/update-article-request';
export type { UpdateMarketingPreferencesRequest } from './models/update-marketing-preferences-request';
export type { UpdateProfileRequest } from './models/update-profile-request';
export type { UpdateShowroomItemPhotoRequest } from './models/update-showroom-item-photo-request';
export type { UpdateShowroomItemRequest } from './models/update-showroom-item-request';
